cargo-features = ["edition2021"]

[package]
name = "app"
version = "0.1.0"

# ring, kriptografi işlemleri için kullanılan bir kütüphane
# libc ise C tarafı ile etkileşimde yardımcı olacak kütüphane
[dependencies]
libc="0.2.107"
ring="0.16.19"